{{- if and .Values.certManager.enabled .Values.certManager.externalSecret -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.certManager.externalSecret.name }}
  namespace: openshift-cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Values.certManager.externalSecret.name }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.certManager.externalSecret.vaultName }}
{{ end }}
