- hosts: localhost
  gather_facts: false
  vars:
    cluster_state: absent
  tasks:
    - name: set platform config fact
      ansible.builtin.set_fact:
        "{{ cluster_platform }}_platform_config": "{{ platform_configs[cluster_platform] }}"

    - name: include vault_config role
      ansible.builtin.include_role:
        name: vault_config

    - name: include gitops_cluster_build role
      ansible.builtin.include_role:
        name: gitops_cluster_build

    - name: include sso_client role
      ansible.builtin.include_role:
        name: sso_client

    - name: include resource_allocation role
      ansible.builtin.include_role:
        name: resource_allocation

    - name: include dns role
      ansible.builtin.include_role:
        name: dns_config
