{{- if .Values.externalSecrets.enabled -}}
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '0'
spec:
  # this must be set to false when using olm
  installCRDs: false
{{ end }}
